version: '3.7'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - "5044:5044"
      - "2256:2256"
      - "50000:50000/tcp"
      - "50000:50000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    networks:
      - elk

  # Log generator
  # Generate logs and split log files every 1000MB in "/logs/*.log" path with "json" format
  # $ flog -t log -f json -o /logs/*.log -p 1000000000
  flog-0:
    image: nityag123/flog:latest
    # Output fake log in JSON format with traces
    command: [ "--format=json_with_trace", "-k", "1500", "--bytes=55500000000"]
    stop_signal: SIGKILL
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:2256"
    depends_on:
      - logstash
  
  flog-1:
    image: nityag123/flog:latest
    # Output fake log in JSON format with traces
    command: [ "--format=json_with_trace", "-k", "1500", "--bytes=55500000000"]
    stop_signal: SIGKILL
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:2256"
    depends_on:
      - logstash
  flog-2:
    image: nityag123/flog:latest
    # Output fake log in JSON format with traces
    command: [ "--format=json_with_trace", "-k", "1500", "--bytes=55500000000"]
    stop_signal: SIGKILL
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:2256"
    depends_on:
      - logstash

networks:
  elk:
    driver: bridge

volumes:
  setup:
