global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'eexporter'
    static_configs:
      - targets: ['eexporter:9114']
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]